Topic/explicit rma
boehms/specification pull request #1
Opened 2017-08-14 16:32 UTC by boehms

2017-08-14 17:05 UTC, manjugv requested changes

2017-08-14 17:05 UTC, manjugv commented on content/explicit_rma_intro.tex
> +routines are the same as for regular \ac{RMA} routines.
This sentence seems redundant.

2017-08-14 17:05 UTC, manjugv commented on content/explicit_rma_intro.tex
> +can be shared.
If the library decides to not provide resources, it is still correct. IMO, assigning of resources is more of motivation than the requirement.

2017-08-14 17:05 UTC, manjugv commented on content/explicit_rma_intro.tex
> +allocation, deallocation and merging of request objects.
Consider merging this paragraph with the first.

2017-08-14 17:05 UTC, manjugv commented on content/shmem_get_nbe.tex
> +void shmem_<TYPENAME>_get_nbe(TYPE *dest, const TYPE *source, size_t nelems, int pe, shmem_request_t *req);
Do you want "req" to be "**" for output ?

2017-08-14 17:05 UTC, manjugv commented on content/shmem_request_allocate.tex
> +    runtime.\\
You should return the error code rather than invalid SHMEM_REQUEST_INVALID. If you go this route, you need add an extra branch in the critical path.

2017-08-14 17:05 UTC, manjugv commented on content/shmem_request_allocate.tex
> +void shmem_request_allocate(shmem_request_t *req, int flags);
Instead of flags, the parameter name with "options" makes sense.

2017-08-14 17:05 UTC, manjugv commented on content/shmem_request_merge.tex
> +\end{Csynopsis}
I think we should not propose the function interface, yet. I don’t see a clear motivation. 
It seems more for completion and usability. What do you think ?

2017-08-14 17:05 UTC, manjugv commented on content/shmem_request_merge.tex
> +    automatically freed. After the function returns the handles are
Missing comma: "After the function returns, the .."

2017-08-14 17:05 UTC, manjugv commented on content/shmem_request_test.tex
> +void shmem_request_test(shmem_request_t *req, int *status);
Do you define the status constants ?

2017-08-14 17:05 UTC, manjugv commented on content/explicit_rma_intro.tex
> +can be shared.
In general, there should be discussion about the semantics in multithreaded environment. Particularly, how the request object is treated in multithreaded environment.

2017-08-14 17:05 UTC, manjugv commented on main_spec.tex
>  \subsubsection{\textbf{SHMEM\_GET\_NBI}}\label{subsec:shmem_get_nbi}
Need to add change log also.

2017-08-14 17:38 UTC, boehms commented on content/shmem_request_merge.tex
> +\end{Csynopsis}
I don't mind leaving this off the table for now.

2017-08-14 17:39 UTC, boehms commented on content/shmem_request_test.tex
> +void shmem_request_test(shmem_request_t *req, int *status);
I have not defined any constants. All I say that the status will be 0 if the request is complete and non zero otherwise.

2017-08-14 17:43 UTC, boehms commented on content/explicit_rma_intro.tex
> +allocation, deallocation and merging of request objects.
Will do

2017-08-14 17:44 UTC, boehms commented on content/shmem_get_nbe.tex
> +void shmem_<TYPENAME>_get_nbe(TYPE *dest, const TYPE *source, size_t nelems, int pe, shmem_request_t *req);
All shmem_request_t's are pointer types so it will be a ** of some sort.

2017-08-14 17:44 UTC, boehms commented on content/shmem_request_allocate.tex
> +void shmem_request_allocate(shmem_request_t *req, int flags);
That sounds more appropriate. I will change it.

2017-08-14 17:46 UTC, boehms commented on content/shmem_request_allocate.tex
> +    runtime.\\
Do you want to define errors here, or just say it will return a negative integer on failure?

2017-08-14 17:48 UTC, boehms commented on main_spec.tex
>  \subsubsection{\textbf{SHMEM\_GET\_NBI}}\label{subsec:shmem_get_nbi}
I will add a change log entry when we think the rest is okay.

2017-08-15 13:57 UTC, boehms commented on content/shmem_request_allocate.tex
> +
@manjugv Do you have any preference on option names here?

2017-08-15 14:52 UTC, manjugv commented on content/shmem_request_allocate.tex
> +    runtime.\\
Negative and Positive is fine.

2017-08-15 14:54 UTC, manjugv commented on content/shmem_request_allocate.tex
> +
SHMEM_HANDLE_PRIVATE, SHMEM_HANDLE_SHAREABLE ?

2017-08-15 14:55 UTC, manjugv commented
In general, I'm still not sure about the semantics and performance, when the handle is shared across the threads.

2017-08-15 18:32 UTC, manjugv commented on content/shmem_request_wait.tex
> +particular request.
The idea is right. However, we should make this more verbose. Probably, later ...

2017-08-15 18:32 UTC, manjugv commented on content/shmem_request_wait.tex
> +    wait was called.
by calling thread, or any thread ? Again, we can address this later.

2017-08-15 18:58 UTC, closed without merging